### ISSUE TITLE
[HUGA] `NOP` action does not advance time

### ISSUE THREAD

**Issue by jhostetler** [StephenGss/PAL#11]
Appendix A.9.a in task spec:
```
9)	API option to advance time without a stepCost: NOP
a.	The command “NOP” can be sent to advance time by one turn without taking an action for the TA2 agent. This could be useful if the Agent wants to wait for a specific future state without changing location. The NOP does not have a stepCost.
```

Command currently does not advance time, in the sense that patrols don't move when executing it. (Note that because of #10 this isn't apparent from the `SENSE_ALL` results, but I was watching visually and the patrols didn't move.)

Possibly not a bug and just a misunderstanding of what "advance time" means, but there doesn't seem to be anything to wait for other than patrols moving.

**Comment by StephenGss** [comment]
This is fixed in the latest version. NOP now advances time and actors will respond
