### ISSUE TITLE
[HUGA] Can't determine color/"opened" state of doors from SENSE_ALL

### ISSUE THREAD

**Issue by jhostetler** [StephenGss/PAL#15]
Doors are indicated in the map.blocks property, but only by the type of the block. Maybe map.blocks could be a list of objects, with fields 'type', 'color', etc.?

**Comment by StephenGss** [comment]
Please use "SENSE_ALL NONAV" to receive extended block info.
Example block door definition 
"63,17,66":{"color":"blue","name":"polycraft:locked_door","isAccessible":true,"facing":"east","half":"lower","hinge":"right","open":"false","powered":"false"}
