### ISSUE TITLE
[POGO] does USE work w/ key on safe??

### ISSUE THREAD

**Issue by musliner** [StephenGss/PAL#34]
Next question: I finally TP_TOd to the safe, key selected, and did 'USE', but the action failed with  "Tried to use hand on air"     .    relevant sensed data: {"blockInFront":{"name":"polycraft:safe","color":"blue","facing":"east"}  "selectedItem":{"slot":0,"item":"polycraft:key","count":1,"damage":4,"maxdamage":0}} 

[2021-10-31 19:00:06] b'{"goal":{"goalType":"ITEM","goalAchieved":false,"Distribution":"Uninformed"},"command_result":{"command":"USE","argument":"","result":"FAIL","message":"Tried to use hand on air","stepCost":300.0},"step":61,"gameOver":false}\n'^M

"player":{"pos":[59,17,78],"facing":"NORTH","yaw":180.0,"pitch":0.0},

Does the agent actually have to be facing the opposite direction of the safe, or something?

@StephenGss

**Comment by StephenGss** [comment]
The use command was working but the response was not. Apparently there was a rounding error in Minecraft code that caused the player's position to round up after teleporting. Everything else still worked as expected.
This has been fixed in the latest update
