### ISSUE TITLE
[POGO] Something changed/broken in pogoist spec in polycraft-1.5.4-20211103-14.13.50.jar ?

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#36]
Yday, I grabbed polycraft-1.5.4-20211103-14.13.50.jar  from commit 15db8b5d52a7c3dc7bd5dff0fda57855580d2dff

A couple of our Phase 2 tests that include a pogoist now fail, eg
[pogoist-goal-fail.log](https://github.com/StephenGss/PAL/files/7476309/pogoist-goal-fail.log)
:

**Comment by StephenGss** [comment]
I made a logic change to pogoist logic that broke backwards compatibility. This has been fixed in the latest update.
