### ISSUE TITLE
[POGO] PLACE_TREE_TAP crash

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#37]
Looks like PAL crashed when our agent placed a tree tap:
`PAL: b'[2021-11-06 10:37:25] [15:37:25] [BOT API THREAD/INFO]: [AGENT]PLACE_TREE_TAP\r\n'
PAL: b'[2021-11-06 10:37:25] [15:37:25] [Client thread/INFO]: [edu.utd.minecraft.mod.polycraft.aitools.BotAPI:onClientTick:643]: PLA\
CE_TREE_TAP\r\n'
PAL: b'[2021-11-06 10:37:25] [15:37:25] [Client thread/INFO]: Running Command on Client side: edu.utd.minecraft.mod.polycraft.aitool\
s.commands.APICommandPlaceBlock\r\n'
PAL: b'[2021-11-06 10:37:25] [15:37:25] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.ga\
meevent.TickEvent$ClientTickEvent@699145b6:\r\n'
PAL: b'[2021-11-06 10:37:25] java.lang.NullPointerException\r\n'
PAL: b'[2021-11-06 10:37:25] \tat edu.utd.minecraft.mod.polycraft.aitools.commands.APICommandPlaceBlock.clientExecute(APICommandPlac\
eBlock.java:151) ~[APICommandPlaceBlock.class:?]\r\n'
`
[pal-tournament-2021-11-06-101257-openmind0.log.gz](https://github.com/StephenGss/PAL/files/7491582/pal-tournament-2021-11-06-101257-openmind0.log.gz)

**Comment by mpatsift** [comment]
Now I see I have more of these.  I've tried a few tournaments running all 100 games in the `pogo_100_PN` directory and they have all died by game 16 with this sort of failure.

**Comment by mpatsift** [comment]
Here's a much shorter run which ends when PAL crashes on a place tree tap.  Unfort, it uses a slightly customized version of one of the shared novelty configs (I removed the pogoist).  Config attached.

When I have some spare time, I'll try this with the unmodified configs.

Thanks,

Mike


[pal-tournament-2021-11-08-133819-openmind-0.log.gz](https://github.com/StephenGss/PAL/files/7499902/pal-tournament-2021-11-08-133819-openmind-0.log.gz)
[POGO_L01_T01_S01_X0100_U0015_V0_G00015_I0628_N3-no-pogoist.json.gz](https://github.com/StephenGss/PAL/files/7499946/POGO_L01_T01_S01_X0100_U0015_V0_G00015_I0628_N3-no-pogoist.json.gz)

**Comment by mpatsift** [comment]
Here's a one game tournament that ends with the place tree tap crash!
[pal-tournament-2021-11-08-190926-openmind1.log.gz](https://github.com/StephenGss/PAL/files/7501395/pal-tournament-2021-11-08-190926-openmind1.log.gz)

It uses the POGO_L01_T01_S01/X0100/POGO_L01_T01_S01_X0100_H_U0015_V0/POGO_L01_T01_S01_X0100_U0015_V0_G00015_I0628_N3.json config from your shared novelties.

**Comment by StephenGss** [comment]
This happened because one of the traders spawned inside a wall and "suffocated"
When placing a block, there is a check that will crash if it can't find an actor. 
The new game configs should fix this.
