### ISSUE TITLE
some problem configs missing iron_pickaxe, making problem unsolvable

### ISSUE THREAD

**Issue by musliner** [StephenGss/PAL#39]
e.g., POGO_L01_T01_S01/X0100/POGO_L01_T01_S01_X0100_E_U0015_V0/POGO_L01_T01_S01_X0100_U0015_V0_G00020_I0092_N1.json
and POGO_L01_T01_S01_X0100_U0015_V0_G00016_I0037_N1.json

without iron_pickaxe, cannot break platinum to trade for titanium, and cannot get enough diamonds to craft/trade past that issue.

I don't know how many other configs this occurs in , but it appears to be a  lack of this block in the json:
      "itemList": [
        {
          "slot": 7,
          "itemDef": {
            "itemName": "minecraft:iron_pickaxe",
            "itemMeta": 0,
            "count": 1
          }
        }

**Comment by StephenGss** [comment]
I just tested these and the player gets an iron pickaxe and it is defined in the file as well.

POGO_L01_T01_S01_X0100_U0015_V0_G00016_I0037_N1-no-pogoist.json:
Can you check lines 2427-2450? You should see the below text
    {
      "pos": [
        3,
        4,
        6
      ],
      "name": "Add Items 6",
      "color": -256,
      "type": "ADD_ITEMS",
      "canProceed": false,
      "isDone": false,
      "completionTime": 0,
      "uuid": "b6ae0b79-e683-4c8a-b33c-39659562c617",
      "itemList": [
        {
          "slot": 1,
          "itemDef": {
            "itemName": "minecraft:iron_pickaxe",
            "itemMeta": 0,
            "count": 1
          }
        }
      ]
    },

And for POGO_L01_T01_S01_X0100_U0015_V0_G00020_I0092_N1.json:
Lines 2552-2575
    {
      "pos": [
        3,
        4,
        6
      ],
      "name": "Add Items 6",
      "color": -256,
      "type": "ADD_ITEMS",
      "canProceed": false,
      "isDone": false,
      "completionTime": 0,
      "uuid": "b6ae0b79-e683-4c8a-b33c-39659562c617",
      "itemList": [
        {
          "slot": 6,
          "itemDef": {
            "itemName": "minecraft:iron_pickaxe",
            "itemMeta": 0,
            "count": 1
          }
        }
      ]
    },

**Comment by musliner** [comment]
i just looked here and see what we have, no pickaxe...is this wrong place?

https://github.com/StephenGss/PAL/blob/release_2.0/shared_novelty/POGO/POGO_L01_T01_S01/X0100/POGO_L01_T01_S01_X0100_E_U0015_V0.zip

**Comment by StephenGss** [comment]
My mistake. I was looking at the files in the pogo_100_PN folder.
This is a conflict between the iron pickaxe and wooden axe novelties. 

I will fix this and update the shared tournament.

**Comment by StephenGss** [comment]
I corrected our generation logic and regenerated the shared novelty game configs. Please update your game configs to the latest version on the repo.
