### ISSUE TITLE
missing trader makes config unsolvable

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#41]
Observed in this config:
`pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00029_I0004_N0.json`

Only one trader appears in game and it does not offer the  platinum -> titanium trade necessary to win game.

I think I may have seen missing traders elsewhere and will keep my eyes open in future.
[pal-tournament-123737-openmind1.log.gz](https://github.com/StephenGss/PAL/files/7540992/pal-tournament-123737-openmind1.log.gz)

**Comment by StephenGss** [comment]
I have corrected our generation logic and updated the game configs. Please replace your pre novelty configs with the latest in the repo
