### ISSUE TITLE
PAL startup failing on etag download from http://export.mcpbot.bspk.rs

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#42]
As reported in earlier email, SIFT can't run PAL starting early today or late yesterday):

AL: b'[2021-11-17 08:14:31] Downloading https://services.gradle.org/distributions/gradle-2.7-bin.zip\r\n'
PAL: b'[2021-11-17 08:14:36] ................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
.............................................................................................................................................................................................................................\
...........................................................\r\n'
PAL: b'[2021-11-17 08:14:36] Unzipping /root/.gradle/wrapper/dists/gradle-2.7-bin/4s0fcuuppw3tjb1sxpzh16mne/gradle-2.7-bin.zip to /root/.gradle/wrapper/dists/gradle-2.7-bin/4s0fcuuppw3tjb1sxpzh16mne\r\n'
PAL: b'[2021-11-17 08:14:36] Set executable permissions for: /root/.gradle/wrapper/dists/gradle-2.7-bin/4s0fcuuppw3tjb1sxpzh16mne/gradle-2.7/bin/gradle\r\n'
PAL: b'[2021-11-17 08:15:11] Etag download for http://export.mcpbot.bspk.rs/versions.json failed with code 522\r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] FAILURE: Build failed with an exception.\r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] * Where:\r\n'
PAL: b"[2021-11-17 08:15:13] Build file '/gradle/polycraft/build.gradle' line: 36\r\n"
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] * What went wrong:\r\n'
PAL: b"[2021-11-17 08:15:13] A problem occurred evaluating root project 'polycraft'.\r\n"
PAL: b'[2021-11-17 08:15:13] > java.lang.NullPointerException (no error message)\r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] * Try:\r\n'
PAL: b'[2021-11-17 08:15:13] Run with --info or --debug option to get more log output.\r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] * Exception is:\r\n'
PAL: b"[2021-11-17 08:15:13] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'polycraft'.\r\n"
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:153)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:491)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:89)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:126)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.internal.Factories$1.create(Factories.java:22)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:123)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.Main.doAction(Main.java:33)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.launcher.GradleMain.main(GradleMain.java:23)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)\r\n'
PAL: b'[2021-11-17 08:15:13] Caused by: java.lang.NullPointerException\r\n'
PAL: b'[2021-11-17 08:15:13] \tat net.minecraftforge.gradle.common.BaseExtension.checkMappings(BaseExtension.java:261)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat net.minecraftforge.gradle.common.BaseExtension.setMappings(BaseExtension.java:240)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat net.minecraftforge.gradle.user.patcherUser.forge.ForgeExtension_Decorated.setMappings(Unknown Source)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:194)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.BeanDynamicObject.setProperty(BeanDynamicObject.java:111)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:104)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat net.minecraftforge.gradle.user.patcherUser.forge.ForgeExtension_Decorated.setProperty(Unknown Source)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat build_aemec2rm22i8ge7g1x2vbddx1$_run_closure1.doCall(/gradle/polycraft/build.gradle:36)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat build_aemec2rm22i8ge7g1x2vbddx1.run(/gradle/polycraft/build.gradle:27)\r\n'
PAL: b'[2021-11-17 08:15:13] \tat org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)\r\n'
PAL: b'[2021-11-17 08:15:13] \t... 50 more\r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] BUILD FAILED\r\n'
PAL: b'[2021-11-17 08:15:13] \r\n'
PAL: b'[2021-11-17 08:15:13] Total time: 41.363 secs\r\n'
PAL: b''

**Comment by StephenGss** [comment]
This was fixed on Thursday evening. Were you able to update and get it working?

**Comment by mpatsift** [comment]
Yes, working now.  Thanks for fixing this quickly!
