### ISSUE TITLE
[POGO] No pickaxe in inventory (or traders in world) when game starts

### ISSUE THREAD

**Issue by rsthielstrom** [StephenGss/PAL#46]
[nopickaxejson.txt](https://github.com/StephenGss/PAL/files/7652598/nopickaxejson.txt)

At the start of seemingly random games in the no-novelty tournament, we sometimes detect the lack of a pickaxe in the inventory. In the JSON above, you can see that the pickaxe is not present on the first step of the game even though all other elements in the world are. The pickaxe does appear in the inventory on the very next SENSE_ALL we perform.

As advised, we tried submitting the command NOP two times before our agent begins the game, and this seemed to fix the problem. However, we are now getting issues with one or more traders not being present in the world at the start of the game, which you can see in the following JSON. The traders don't seem to appear even after several SENSE_ALLs.

[notradersjson.txt](https://github.com/StephenGss/PAL/files/7678593/notradersjson.txt)

Here's the PAL log for that game as well.

[PAL_log_game_52_2021-12-08_17_58_56.txt](https://github.com/StephenGss/PAL/files/7678602/PAL_log_game_52_2021-12-08_17_58_56.txt)

**Comment by musliner** [comment]
we've seen this too.... see ref in https://github.com/StephenGss/PAL/issues/53   ...not sure if we've seen traders actually disappear in middle of game, I think all our logging of UNEXPECTED-NUMBER-OF-TRADERS when they are missing is at start of game.  If they disappear in middle, we might report other novelties...

**Comment by StephenGss** [comment]
This has been fixed in 5609c07d1e677f1e3ab1616a9a97c1a8c3526f88
I've made the traders and pogoists invulnerable and added a check for items before an experiment can begin
