### ISSUE TITLE
[HUGA] Teleport-to-start triggered in between agent actions when standing next to trap

### ISSUE THREAD

**Issue by jhostetler** [StephenGss/PAL#50]
In 550b72faa2098fc4855e87d437f504a9d70e5139, the teleport-to-start event can trigger while standing **next to** a trap (8-neighborhood), and this happens **independently of agent actions** (i.e., the teleport can happen while the agent is standing there waiting to choose its next action, after it has already received an observation from the environment but before taking the next action).

Bug was not present in d455ccba10ccb5d1d44bcc5eb9023646de2e843d

**Comment by StephenGss** [comment]
This has been fixed. There was an issue with the distance calculation between traps.
