### ISSUE TITLE
Pogoist disappears from the environment

### ISSUE THREAD

**Issue by EricKildebeck** [StephenGss/PAL#53]
Reported by Ravenna/Evan on 12/16:

" This is in the medium pogoist trades games (5-1-1). Initially the pogoist is in the environment, but at some point disappears entirely and is not in the senseall json. Our agent is in the main room (traders are there), but there's no pogoist. It happens in  
  POGO_L05_T05_S01_X0100_M_U0015_V0_G00016_I0337_N2.json and likely others too"

**Comment by musliner** [comment]
We see the trader disappearing sometimes too, at seemingly random times.   Can provide logs on request.... our agent log says UNEXPECTED-NUMBER-OF-TRADERS when this happens...    This tends to confuse our agent and sometimes it fails to make pogostick after this happens.   for-sift-info, example at musliner@openmind0:~/openmind/code/test/results/m4-nopogoist-POGO-L20-T01-S01-U0100-E-K0010-V1-2022-02-24-103729-openmind0$
