### ISSUE TITLE
[HUGA] Enemies might move between SENSE_ALL and the SAIL-ON agent's action

### ISSUE THREAD

**Issue by jhostetler** [StephenGss/PAL#56]
This is possibly just a manifestation of #55, or it might be a separate issue. In the attached log, on line 18911, the SAIL-ON agent is facing left and there is a gray patrol (`Y`) to its right. The SAIL-ON agent executes a "move forward" action (line 18961), but it doesn't actually move, and in the next frame, the gray patrol is in front of it and has apparently blocked the move (line 18987). This is reported as a novelty (line 18965) because the move command was expected to succeed
[HUGA_L00_T01_S01_X0100_A_U9999_V0-entity-moves-before-agent.log](https://github.com/StephenGss/PAL/files/8029281/HUGA_L00_T01_S01_X0100_A_U9999_V0-entity-moves-before-agent.log)
.

**Comment by EricKildebeck** [comment]
My understanding is that this is very similar to the MacGuffin issue we ran into in Phase 1. These race condition are something that in the current iteration happen in the base Minecraft communication between the server and client. We continue to look into paths to change that, but it is fundamentally different than the other bugs that result from our additional Polycraft code and we can fix easily.

The agents movement is a similar, albeit more complex, instance of the MacGuffin issue. The workarounds for the MacGuffin may be a good solution if the 200ms delay is not suitable.
