### ISSUE TITLE
Traders never appear in game

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#57]
[pal-tournament-2022-03-16-150756-openmind0.gz](https://github.com/StephenGss/PAL/files/8289648/pal-tournament-2022-03-16-150756-openmind0.gz)

Both traders never appear in the the third game of this tournament, using config POGO_L06_T03_S01_X0100_E_U0015_V0_G00016_I0037_N1.json and starting at log line 6470.

I've run this tournament configuration several times and have not seen this happen before.

**Comment by StephenGss** [comment]
It's hard to replicate and unreliable, but I put in a check to make sure the entities are loaded. 
Apparently they are still there, just not loaded in the right places in the code.
This is fixed in d587e7994ec4e1544a5e3b1134c256972f930e64

**Comment by mpatsift** [comment]
Looks like it's fixed.  I tried running this tournament several times and did not see this bug occur.
