### ISSUE TITLE
Pogoist (acting as trader in revealed novelty 5-5-1-M) disappears from game

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#59]
During some (but not all) runs I've done using config `POGO_L05_T05_S01_X0100_M_U0015_V0_G00015_I0328_N2.json` the pogoist disappears from the game, making the game unsolvable (our agent needs to trade with the pogoist to make a pogo stick).

This viz shows the game right after the pogoist has left the building.  Its last observed command was `TP_TO 1,4,2`, which, I'm pretty sure, would jump it out of the room and out of the ground plane.

![bridge log gz line_11040 2022-03-24_15 38 19_GAME1](https://user-images.githubusercontent.com/13005513/160464962-9a8960d3-f80f-4a31-8373-a4011dba0c41.svg)

Here's the pal-tournament.log, but I didn't see anything telling:

[pal-tournament-log-pal-tournament-v2-shared-5-5-1-M-2022-03-24-153401-openmind0.gz](https://github.com/StephenGss/PAL/files/8365451/pal-tournament-log-pal-tournament-v2-shared-5-5-1-M-2022-03-24-153401-openmind0.gz)

UPDATE: looking more closely at the other games in this tournament, I see the pogoist disappearing and (sometimes) reappearing in all the novel games.  In most games the pogoist disappears for good after executing a `TP_TO 1,4,2`.

(For sift ref: pal-tournament-v2-shared-5-5-1-M-2022-03-24-153401-openmind0)

**Comment by mpatsift** [comment]
I tried using some other configs, but no change.  This seems to be a predictable pattern:
- Pogoist hangs around TVs for a while
- Pogoist disappears
- Pogoist reappears around TVs
- Pogoist disappears for good (usually with last action reported as `TP_TO 1,4,2`)

Sometimes our agent manages to complete its required trades before the pogoist disappears.

I haven't seen the Pogoist around the crafting table (as described in 5-5-1-M doc).  Possibly a problem w whatever code implements the pogoist movement for this novelty?

**Comment by StephenGss** [comment]
Hi Matt.
Thanks for the excellent documentation on this. 
The pogoist was teleporting to the wrong location. I fixed this in d587e7994ec4e1544a5e3b1134c256972f930e64
Now it should go to the crafting table, wait 4 actions, then back to the traders and repeat.

**Comment by mpatsift** [comment]
Thanks, Steven!  I will try out the new version today.  I think all three of those bugs have shown up in our tests recently.

Thanks,

Mike

**Comment by mpatsift** [comment]
Works at SIFT using https://github.com/StephenGss/PAL/commit/a92e35e3c4750892f7f876ab6ee861860d6296dd

Thanks!
