### ISSUE TITLE
[POGO] Most recent commit (d587e79) crashes in v2 games at SIFT

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#61]
Our v2 tournaments are crashing with the latest jar: polycraft-1.5.4-20220405-13.38.47.jar 

The ones I've looked at are all similar:  crashing a few steps after the first break_block on a log.  Poss when sapling would appear?
[pal-tournament-v2-shared-5-5-1-M-2022-04-06-110306-openmind0.log.gz](https://github.com/StephenGss/PAL/files/8429565/pal-tournament-v2-shared-5-5-1-M-2022-04-06-110306-openmind0.log.gz)

(SIFT ref: /home/mpelican/projects/openmind/trunk/code/test/results/pal-tournament-v2-shared-5-5-1-M-2022-04-06-110306-openmind0 )

**Comment by StephenGss** [comment]
Could you share the game config?

**Comment by mpatsift** [comment]
(This is actually a different example.  I screwed up the other log file somehow while compressing, renaming, uploading.)

log file:
[pal-tournament-v2-shared-1-1-1-E-2022-04-06-132655-openmind0.log.gz](https://github.com/StephenGss/PAL/files/8429868/pal-tournament-v2-shared-1-1-1-E-2022-04-06-132655-openmind0.log.gz)

config:
[POGO_L01_T01_S01_X0100_E_U0015_V0_G00000_I0020_N0.json.gz](https://github.com/StephenGss/PAL/files/8429876/POGO_L01_T01_S01_X0100_E_U0015_V0_G00000_I0020_N0.json.gz)

(SIFT ref: /home/mpelican/projects/openmind/trunk/code/test/results/pal-tournament-v2-shared-1-1-1-E-2022-04-06-132655-openmind0 )

**Comment by StephenGss** [comment]
Thanks, That makes more sense with the behavior in the logs.
I've replicated the issue. Working on a fix now.

**Comment by StephenGss** [comment]
I pushed a fix in 326db4b2266b2ca7e582ea8ace6c03f229e65d49
This also fixed a potential bug where the pogoist can break two trees in the same action.

**Comment by mpatsift** [comment]
Thanks.  I'll give it a spin

**Comment by mpatsift** [comment]
Works at SIFT using https://github.com/StephenGss/PAL/commit/a92e35e3c4750892f7f876ab6ee861860d6296dd
