### ISSUE TITLE
[POGO] Double speed pogoist?

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#62]
Could one of the last couple commits have speeded up the pogoist?

Same tournament, running same configs:

* OLD -- In this run from a week ago, pogoist took at least 114 steps to get
rubber in second game.

[pal-tournament-v2-nonov-3-games-2022-03-31-134459-openmind0.log.gz](https://github.com/StephenGss/PAL/files/8448041/pal-tournament-v2-nonov-3-games-2022-03-31-134459-openmind0.log.gz)

( SIFT ref: /home/mpelican/projects/openmind/trunk/code/test/results/pal-tournament-v2-nonov-3-games-2022-03-31-134459-openmind0 )

* NEW -- In this run today testing
  https://github.com/StephenGss/PAL/commit/09464e4c39590c4198b34aa736751cecc2631423
  pogoist has rubber by step 53.
  

[pal-tournament-v2-nonov-3-games-2022-04-07-163900-openmind0.log.gz](https://github.com/StephenGss/PAL/files/8448048/pal-tournament-v2-nonov-3-games-2022-04-07-163900-openmind0.log.gz)

( SIFT ref: /home/mpelican/projects/openmind/trunk/code/test/results/pal-tournament-v2-nonov-3-games-2022-04-07-163900-openmind0
)

**Comment by StephenGss** [comment]
Hi,
I tested this with an agent that teleports and I get a similar result. 
The pogoist gets to rubber in about 25 non-ignored agent actions and about 50 to craft the pogo stick.

This could be because of the fix that stops the pogoist from moving immediately after teleporting. That could have been slowing down the pogoist quite a bit

**Comment by mpatsift** [comment]
Can the pogoist speed be reverted w/o re-introducing the bug?

This is a huge change for us just two weeks before eval.

**Comment by StephenGss** [comment]
I talked to Eric about it and we agreed to just reintroduce the bug. It will be difficult to get the same logic without significantly changing how the task works.
We will fix the bug after the phase 2 evals are over.

**Comment by mpatsift** [comment]
OK.

Thanks for understanding!

I'll grab asap.

Thanks,

Mike

**Comment by StephenGss** [comment]
Well give me a second to push the update lol
It's up in the latest commit - a92e35e3c4750892f7f876ab6ee861860d6296dd

**Comment by mpatsift** [comment]
Looks good at SIFT.
