### ISSUE TITLE
[HUGA] Some of the L06 shared novelties are unsolvable

### ISSUE THREAD

**Issue by jhostetler** [StephenGss/PAL#66]
In the following instances, none of the chests in the starting room contain the key needed to exit the room:

HUGA_L06_T01_S01_X0100_E_U0017_V1_G00050_I0174_N1
HUGA_L06_T01_S01_X0100_E_U0017_V1_G00051_I0109_N1
HUGA_L06_T01_S01_X0100_E_U0017_V1_G00052_I0177_N1
HUGA_L06_T01_S01_X0100_M_U0013_V2_G00050_I0455_N2

Not sure how widespread this issue is. These are the only 4 I had time to try.

**Comment by StephenGss** [comment]
This is fixed in f4909adbbd41087ad57e097b6f190303055e5675
