### ISSUE TITLE
[HUGA] Not possible to select keys by color?

### ISSUE THREAD

**Issue by jhostetler** [StephenGss/PAL#7]
The `SELECT_ITEM` command takes the item type as argument. Since all of the "key" items have the same type (`polycraft:key`), it seems like it's not possible to select a specific color of key if you have more than one in your inventory.

**Comment by StephenGss** [comment]
You need to first select the item with “select_item polycraft:key 1” to select the red key for example. The 1 in the command is the damage value of the key that’s returned in sense_all or sense_inventory.
